from __future__ import annotations

import logging
from typing import Any, Dict, Optional, Union

from .api import IntercomAPI

_LOGGER = logging.getLogger(__name__)


class RubetekPanelIntercomAPI(IntercomAPI):
    """Rubetek panel authorization profile.

    This class intentionally isolates panel-only behavior from the legacy
    phone/SMS IntercomAPI flow. Shared REST methods, token refresh and media
    helpers continue to live in IntercomAPI.
    """

    def __init__(
        self,
        base_url: str = "https://api.domonap.ru",
        instance_id: Optional[str] = None,
    ) -> None:
        super().__init__(
            base_url=base_url,
            instance_id=instance_id,
            device_platform="panel",
            dom_app="panel",
        )
        # The AOSP/Rubetek panel flow has no FCM/HMS device token. Do not use
        # the synthetic mobile token generated by the common base class.
        self.device_token = None
        self.panel: Dict[str, Any] = {}

    async def confirm_panel_authorization(
        self, confirm_code: str
    ) -> Dict[str, Any]:
        """Exchange the 8-digit provisioning code for a Panel session."""
        result = await self._post(
            "/sso-api/Authorization/ConfirmAuthorizationCode",
            {"confirmCode": confirm_code},
            need_auth=False,
            expect="json",
        )
        if isinstance(result, dict) and "error" in result and "status" in result:
            return result

        try:
            complete_token = result["completeToken"]
            self.panel = dict(result.get("panel") or {})
            self.set_tokens(
                complete_token["accessToken"],
                complete_token["refreshToken"],
                complete_token["refreshExpirationDate"],
            )
            if self.token_update_callback:
                self.token_update_callback(
                    complete_token["accessToken"],
                    complete_token["refreshToken"],
                    complete_token["refreshExpirationDate"],
                )
        except Exception as err:
            _LOGGER.exception("Unexpected panel authorization response: %s", err)
        return result

    async def logout(self) -> Dict[str, Any]:
        """Explicitly invalidate a panel session.

        Runtime unload/restart must not call this; refresh token persistence is
        identical to the regular API session lifecycle.
        """
        if not self.refresh_token:
            return {"ok": True, "skipped": True}
        refresh_token = self.refresh_token
        result = await self._post(
            "/sso-api/Authorization/Logout",
            {"refreshToken": refresh_token},
            need_auth=False,
            expect="text",
            retry_on_401=False,
        )
        if isinstance(result, dict) and "error" in result:
            return result
        self.set_tokens(None, None, None)
        if self.token_update_callback:
            self.token_update_callback(None, None, None)
        return {"ok": True, "body": result}
